name: 'dbt_first_project'
model-paths: ["models"]
models: 
  materialized: 'view'
seed-paths: ["seeds"]
analysis-paths:
  - "analysis"
macro-paths:
  - "macros"
snapshot-paths:
  - "snapshots"
test-paths:
  - "tests"
  


